GET http://localhost:3000/todos-filmes
###

###
POST http://localhost:3000/create-filmes
Content-Type: application/json

{
    "title": "Alice no país das maravilhas",
    "genre": "Fantasia",
    "duration": 152,
    "age_rating": "Livre"
}

###
DELETE http://localhost:3000/delete-filmes/3

###
PUT http://localhost:3000/update-filmes/1
Content-Type: application/json

{
    "title": "Shrek 2",
    "genre": "Animação",
    "duration": 93,
    "age_rating": "Livre"
}